added element change to MCS
OpenFreeEnergy/Lomap pull request #15
Opened 2022-06-23 15:58 UTC by richardjgowers

2022-06-23 15:58 UTC, pep8speaks commented
Hello @richardjgowers! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`lomap/mcs.py`](https://github.com/OpenFreeEnergy/Lomap/blob/dbb0895fe70b3722e82dbf261c50248ddc2ff610/lomap/mcs.py):

> [Line 1086:49](https://github.com/OpenFreeEnergy/Lomap/blob/dbb0895fe70b3722e82dbf261c50248ddc2ff610/lomap/mcs.py#L1086): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 1087:72](https://github.com/OpenFreeEnergy/Lomap/blob/dbb0895fe70b3722e82dbf261c50248ddc2ff610/lomap/mcs.py#L1087): [E202](https://duckduckgo.com/?q=pep8%20E202) whitespace before ']'
> [Line 1088:80](https://github.com/OpenFreeEnergy/Lomap/blob/dbb0895fe70b3722e82dbf261c50248ddc2ff610/lomap/mcs.py#L1088): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (148 > 79 characters)
> [Line 1088:95](https://github.com/OpenFreeEnergy/Lomap/blob/dbb0895fe70b3722e82dbf261c50248ddc2ff610/lomap/mcs.py#L1088): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 1088:147](https://github.com/OpenFreeEnergy/Lomap/blob/dbb0895fe70b3722e82dbf261c50248ddc2ff610/lomap/mcs.py#L1088): [E202](https://duckduckgo.com/?q=pep8%20E202) whitespace before ']'





##### Comment last updated at 2022-06-27 19:24:49 UTC

2022-06-23 16:36 UTC, dwhswenson reviewed
A couple issues related to SemVer.

Also, would there be any reason to allow users to also pass another rdkit AtomCompare, rather than just limiting it to these two options?

2022-06-23 16:38 UTC, dwhswenson commented on lomap/mcs.py
> +           Added element_change kwarg
Wait, nvm.. I misread which was the old default

2022-06-23 16:45 UTC, richardjgowers commented
Yeah we could allow an arbitrary `AtomCompare`, but then I'd need to think of representative tests for all the members of the enum

2022-06-24 17:10 UTC, IAlibay requested changes
Couple of small things - mostly some docs things

I understand that CompareAny will just take any atoms in the comparison, I assume CompareElements will restrict this to only alike elements, but I can't find the actual docs for it.

2022-06-24 17:21 UTC, dwhswenson commented on lomap/mcs.py
> +            atom_compare = rdFMCS.AtomCompare.CompareElements
I believe this is the actual cocde doing the work: https://github.com/rdkit/rdkit/blob/94cde75973ec423d44996f0d47352b4fe4e3a90a/Code/GraphMol/FMCS/FMCS.cpp#L247-L330

2022-06-24 17:26 UTC, IAlibay commented on lomap/mcs.py
> +            atom_compare = rdFMCS.AtomCompare.CompareElements
Awesome thanks, that makes sense now :)

2022-06-27 14:50 UTC, IAlibay commented on lomap/dbmol.py
> +                 time=20, ecrscore=0.0, threed=False, max3d=1000.0,
Given CI didn't fail, I assume this isn't covered by tests at all?

2022-06-27 14:52 UTC, IAlibay approved these changes
Just the one thing, I'll approve now rather than block.

2022-06-27 14:52 UTC, IAlibay commented on lomap/mcs.py
> +            this distance, default 1,000.0
```suggestion
            this distance (in units of Angstrom), default 1,000.0
```

2022-06-27 19:26 UTC, IAlibay commented
@richardjgowers I'm going to go ahead and merge this unless you object in the next ~ 30 mins (I want to do some lomap tests tonight)

2022-06-27 21:43 UTC, merged